### PR TITLE
Add Codecov

### LINKED ISSUE #56: Reduce feedback time from the testsuite
On my 16-core AMD Ryzen workstation, the testsuite takes 40 min to run, which is unreasonable. For comparison, the ESPResSo testsuite takes 3 min to run 196 tests on my workstation, or 5 min when all 15 thermalization and titration tests are included.

I'm afraid contributors will be unwilling to run the pyMBE testsuite after each commit due to how long it takes for it to complete. That will lead to contributors getting their inbox flooded with automated e-mails about failing tests, which can be demotivating. Reviewers will also have a harder time verifying code contributions, since the PR will have a lot of small commits to fix regressions introduced in larger commits, thus increasing noise.

We could separate the testsuite into unit tests that provides fast feedback and acceptance tests that verify the reproducibility of published papers. The unit tests should run on every PR. The acceptance tests should run once in a month on the main branch, with the possibility of manually triggering the job via e.g. [`workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow). The latter is important, as contributors or reviewers may want to occasionally check if changes to acceptance tests did not break something by manually triggering the job. Likewise, every time a software release is made, maintainers should manually trigger the acceptance tests to show the release passes all tests.

Acceptance tests might fail once in a while on the main branch, when a regression is accidentally merged on the main branch. Maintainers should react to such a failing pipeline within the next 30 days. When unit tests pass, and the code covered by unit tests is large, then failing acceptance tests are an indication that something extremely subtle is broken. This type of issue requires a long investigation that may exceed the time budget or skill level of most contributors. The community should be allowed to continue opening PRs and getting them merged while experts investigate the broken acceptance tests.

For illustration purposes, historically in ESPResSo, acceptance tests broke due to correlated RNG noise in the Langevin thermalization code (2 afternoons and 3 core developers to debug it), rejected Monte Carlo moves that didn't restore the original particle velocities (1 core developer and 2 external Monte Carlo experts to debug it), incorrect unit conversion in the LB particle coupling code (2 months and 2 cores developers to solve it).

### PR DESCRIPTION
**Pull request by jngrad**
Description of changes:
- move slow tests to a scheduled job called `samples`
   - fixes  #56
   - the workflow can also be triggered manually
- add code coverage in CI using the Codecov GitHub Action
- add test cases (partial fix for #58)

### CODE REVIEW

**Comment by jngrad** [comment]
The `pyMBE.py` script has 55% code coverage at the time of writing. Here is the list of features that require our attention:

* [x] `pymbe_library.NumpyEncoder.default()`
* [ ] `pymbe_library.enable_motion_of_rigid_object()`
* [ ] `pymbe_library.assign_molecule_id()` for the empty residue name edge case
* [ ] `pymbe_library.calculate_HH()` for the case where a molecule has no sequence
* [ ] `pymbe_library.calculate_net_charge()`
* [ ] `pymbe_library.create_added_salt()`
* [ ] `pymbe_library.create_counterions()`
* [ ] `pymbe_library.create_protein()`
* [ ] `pymbe_library.create_residue()` for residue types
* [ ] `pymbe_library.define_AA_particles_in_sequence()`
* [ ] `pymbe_library.define_epsilon_value_of_particles()`
* [ ] `pymbe_library.define_particles_parameter_from_dict()`
* [ ] `pymbe_library.define_protein()`
* [ ] `pymbe_library.destroy_pmb_object_in_system()`
* [ ] `pymbe_library.determine_reservoir_concentrations()`
* [ ] `pymbe_library.generate_coordinates_outside_sphere()`
* [ ] `pymbe_library.generate_random_points_in_a_sphere()` for the case inside the sphere
* [ ] `pymbe_library.get_particle_id_map()`
* [ ] `pymbe_library.get_radius_map()`
* [ ] `pymbe_library.load_interaction_parameters()` for a FENE bond
* [ ] `pymbe_library.parse_sequence_from_file()`
* [ ] `pymbe_library.print_reduced_units()`
* [ ] `pymbe_library.protein_sequence_parser()` for non-standard cases
* [ ] `pymbe_library.read_protein_vtf_in_df()`
* [ ] `pymbe_library.search_particles_in_residue()`
* [ ] `pymbe_library.setup_cpH()`
* [ ] `pymbe_library.setup_gcmc()`
* [ ] `pymbe_library.setup_grxmc_reactions()`
* [ ] `pymbe_library.setup_grxmc_unified()`
* [ ] `pymbe_library.setup_particle_sigma()`
* [ ] `pymbe_library.write_output_vtf_file()`
* [ ] `lib.analysis.add_data_to_df()`
* [ ] `lib.analysis.analyze_time_series()`
* [ ] `lib.analysis.do_binning_analysis()`
* [ ] `lib.analysis.merge_time_series_dfs()`
* [x] `lib.analysis.get_params_from_dir_name()`
* [ ] `lib.analysis.split_dataframe_in_equal_blocks()`
* [ ] `lib.analysis.split_dataframe()`
* [ ] `lib.analysis.get_time_series_from_average_df()`
* [ ] `lib.analysis.block_analyze()`
* [ ] `lib.analysis.get_dt()`
* [ ] `lib.analysis.read_csv_file()`
* [ ] `lib.analysis.get_distribution_from_df()`
* [ ] `lib.analysis.create_histogram_df_from_distribution_list()`
* [ ] `lib.analysis.find_index_with_value_in_df()`
* [x] `lib.analysis.built_output_name()`

If we could get every pyMBE community member to contribute unit tests for 5 features and invest no more than 20 min of developer time per unit test, we should be able to reach 90% code coverage in `pyMBE.py` in about a week. We don't need to write simulation scripts, just a few `np.testing.assert_allclose()` or `pd.testing.assert_frame_equal()` checks. Convenience scripts under the `lib/` folder might require more effort, since they need either synthetic data or a minimal ESPResSo simulation script as input.

The report is available [online](https://app.codecov.io/gh/jngrad/pyMBE/tree/codecov). You can generate the code coverage report locally with the following commands:

```sh
make unit_tests COVERAGE=1
make coverage_html
firefox coverage/index.html
```

Here are the badges for the Readme file:

GitHub Actions [codecov](https://codecov.io/gh/jngrad/pyMBE)

This draft PR will be rebased once all dependency issues are sorted out. It is currently designed around Codecov, because I'm already familiar with this service, but I am open to alternatives. For completeness, here are the main competing services: [Codecov](https://github.com/marketplace/actions/codecov), [Coveralls](https://github.com/marketplace/actions/coveralls-github-action), [Codacy](https://github.com/marketplace/actions/codacy-analysis-cli). Here is a [brief comparison](https://codefresh.io/blog/comparison-code-analysis-tools/) of these services.

**Comment by pm-blanco** [comment]
@jngrad a million thanks for addressing this point. I would add this to our tomorrow's meeting schedule so we can start splitting the workload of developing the tests.

**Comment by jngrad** [comment]
@pm-blanco While we wait for the Pylint PR to be merged, could you please give Codecov access to the pyMBE organization? Right now I'm using my own Codecov token, which means only the commits on my fork can upload coverage reports. Here is the official [quick start](https://docs.codecov.com/docs/quick-start) page. You will need to follow step 1 using your GitHub account to sign up and establish access rights (the app needs to get read access to the organization and write access to write a green check mark in the commit metadata) and step 2 to store the secret token in the pyMBE-dev/pyMBE repository settings. That's it. The YAML file described in step 2 is already available in this PR. Steps 3-6 are already done in this PR too.

**Comment by pm-blanco** [comment]
@jngrad I belive it should be done now!

**Comment by jngrad** [comment]
The code coverage reports are now uploaded to https://app.codecov.io/gh/pyMBE-dev/pyMBE and written to the commit status (green checkmark or red cross). New features require a unit test, otherwise code coverage will drop and CI will fail.

Things to keep in mind:
* for branches from this repository, the secret token is used, and uploads always succeed
* for PRs from forks, the secret token isn't revealed for security reasons, and tokenless mode is used: uploads may fail
   * GitHub has a shared pool of free actions for tokenless users; when exhausted, wait for it to refill and re-run job
   * action log: `Upload failed: {"detail":"Tokenless has reached GitHub rate limit. Please upload using a token: https://docs.codecov.com/docs/adding-the-codecov-token. Expected available in 358 seconds."}`
   * using [OpenID Connect](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect) probably would not help us here, because it requires a secret too (for implementation details: [`codecov-action@d42a336:src/buildExec.ts#L47-L54`](https://github.com/codecov/codecov-action/blob/d42a336584211c4f940f39382853503887003197/src/buildExec.ts#L47-L54))
* the `samples` job runs long tests and samples that reproduce paper results
   * runs biweekly at 6:20 AM to avoid rush hours: cron schedule [`20 6 5,20 * *`](https://crontab.guru/#20_6_5,20_*_*)
      * scheduled workflows may start several minutes late if the rush hour is too strong, and might be cancelled if there isn't enough cloud capacity to absorb the backlog (quite rare, https://www.githubstatus.com/)
      * rush hour is every hour at 0 min, hence the extra 20 min
   * can be manually triggered
      * the manual action will only become visible in the Action tab once the workflow is part of the `main` branch!
      * I can confirm it works on branches, but I haven't tried on PRs (which are actually branches with a prefix)

**Review by pm-blanco — APPROVED** [review]
Looks excellent to me, thank you very much @jngrad. With this PR now we can proceed to develop more unit tests for pyMBE more efficiently. I added the information in this PR to our [wiki](https://github.com/pyMBE-dev/pyMBE/wiki) so it can  be consulted by all contributors.

**Pull request merged**
