### PR TITLE
Make the ionic product an attribute of pyMBE

### PR DESCRIPTION
**Pull request by davidbbeyer**
Solves #45 @pm-blanco

### CODE REVIEW

**Comment by pm-blanco** [comment]
@davidbbeyer I think that it would be better to name the varible consistently `Kw` rather than having different variable names in 
```python
def __init__(self, temperature=None, unit_length=None, unit_charge=None, ionic_product=None)
```
and in `pmb.Kw`.  Also the name `ionic_product` sounds a bit vague to me, as it could refer to some other ionic product than that or water (for example for a precipitation reaction). 

Could you clean the history of your repository? It seems that you have some old commits from the GCMC implementation that are squashed in the principal repo.

**Comment by kosovan** [comment]
I strongly support naming the variables as close as possible to the symbols used in Equations.

**Comment by kosovan** [comment]
I also agree that `ionic_product` is much more ambiguous than Kw.

**Comment by davidbbeyer** [comment]
@pm-blanco I have adjusted the nomenclature accordingly. It is probably easiest if you just squash it before merging. I will properly sync my fork after the merge then.

**Comment by pm-blanco** [comment]
@davidbbeyer the problem with squashing this commits is that then we will have repeated commits in two squashed PR (this one and the previous one) which will mess the history of our repository. I know is a bit tedious, but I think that it would be better if you can solve it before merging this to the main repo.

**Comment by davidbbeyer** [comment]
@pm-blanco Now it should be cleaned up properly :)

**Review by pm-blanco — APPROVED** [review]
it looks good to me

**Pull request merged**
